services:
  - type: web
    name: arac-talep
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arac-talep-db
          property: connectionString
