services:
  - type: web
    name: arac-talep
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    preDeployCommand: >
      python manage.py createsuperuser --noinput --username admin --email admin@example.com
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arac-talep-db
          property: connectionString
