# Generated by Django 5.2 on 2025-05-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AracTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baskanlik', models.CharField(choices=[('SHB', 'Sağlık Hizmetleri Başkanlığı'), ('DHB', 'Destek Hizmetleri Başkanlığı'), ('HSB', 'Halk Sağlığı Başkanlığı'), ('KHB', 'Kamu Hastaneleri Başkanlığı'), ('MB', 'Müdürlük Bünyesi')], max_length=50)),
                ('birim', models.CharField(max_length=100)),
                ('gorev_aciklamasi', models.TextField()),
                ('kisi_sayisi', models.PositiveIntegerField()),
                ('gidis_tarihi', models.DateField()),
                ('gidis_saati', models.TimeField()),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('talep_eden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EkKisiBilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('unvan', models.CharField(max_length=100)),
                ('talep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_kisiler', to='talep.aractalep')),
            ],
        ),
    ]
