# Generated by Django 5.2 on 2025-05-06 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0002_aractalep_ekkisibilgisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalepOnay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], max_length=20)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('onay_tarihi', models.DateTimeField(auto_now_add=True)),
                ('talep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talep_onay', to='talep.aractalep')),
            ],
        ),
    ]
