# Generated by Django 5.2 on 2025-05-06 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0003_taleponay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20, unique=True)),
                ('marka_model', models.CharField(max_length=100)),
                ('kapasite', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='taleponay',
            name='sofor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atandigi_sofor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taleponay',
            name='arac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talep.arac'),
        ),
    ]
