# Generated by Django 5.2 on 2025-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0004_arac_taleponay_sofor_taleponay_arac'),
    ]

    operations = [
        migrations.AddField(
            model_name='aractalep',
            name='gidilecek_ilce',
            field=models.CharField(default='Belirtilmedi', max_length=100),
            preserve_default=False,
        ),
    ]
