# Generated by Django 5.2 on 2025-05-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0005_aractalep_gidilecek_ilce'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aractalep',
            name='gidilecek_ilce',
            field=models.CharField(default='Belirtilmedi', max_length=100),
        ),
    ]
