# Generated by Django 5.2 on 2025-05-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0006_userprofile_telefon_alter_aractalep_gidilecek_ilce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sofor',
            fields=[
            ],
            options={
                'verbose_name': 'Şoför',
                'verbose_name_plural': 'Şoförler',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('talep.userprofile',),
        ),
    ]
