# Generated by Django 5.2 on 2025-05-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0007_sofor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sofor',
        ),
        migrations.CreateModel(
            name='Sofor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
            ],
        ),
    ]
