# Generated by Django 5.2 on 2025-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0008_delete_sofor_sofor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arac',
            name='kapasite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arac',
            name='marka_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
