# Generated by Django 5.2 on 2025-05-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0010_alter_taleponay_sofor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aractalep',
            name='talep_eden_adsoyad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
