# Generated by Django 5.2 on 2025-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0011_aractalep_talep_eden_adsoyad'),
    ]

    operations = [
        migrations.AddField(
            model_name='taleponay',
            name='varis_saati',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taleponay',
            name='durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('tamamlandi', 'Tamamlandı')], max_length=20),
        ),
    ]
