# Generated by Django 5.2 on 2025-05-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0012_taleponay_varis_saati_alter_taleponay_durum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telefon',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
