# Generated by Django 5.2 on 2025-05-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0013_remove_userprofile_telefon_userprofile_ad_soyad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ad_soyad',
            new_name='adsoyad',
        ),
    ]
