# Generated by Django 5.2 on 2025-05-16 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0015_ekkisibilgisi_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aractalep',
            name='uzman_onay_durumu',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='bekliyor', max_length=20),
        ),
        migrations.AddField(
            model_name='aractalep',
            name='uzman_onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzman_onayladigi_talepler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aractalep',
            name='uzman_red_aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
