# Generated by Django 5.2 on 2025-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0016_aractalep_uzman_onay_durumu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('personel', 'Personel'), ('bas_sofor', 'Baş Şoför'), ('mudur', 'Müdür'), ('uzman', 'Uzman / Şube Müdürü')], max_length=20),
        ),
    ]
