# Generated by Django 5.2 on 2025-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0017_alter_userprofile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='taleponay',
            name='iptal_aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taleponay',
            name='durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], max_length=20),
        ),
    ]
