# Generated by Django 5.2 on 2025-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0018_taleponay_iptal_aciklama_alter_taleponay_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='aractalep',
            name='uzman_onay_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taleponay',
            name='atama_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taleponay',
            name='yonetici_onay_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
