# Generated by Django 5.2 on 2025-05-22 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0019_aractalep_uzman_onay_tarihi_taleponay_atama_tarihi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('arac', models.CharField(max_length=50)),
                ('sofor', models.CharField(max_length=50)),
                ('gorev_aciklamasi', models.TextField()),
                ('ek_kisiler', models.ManyToManyField(blank=True, to='talep.userprofile')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
